### ISSUE TITLE
No documentation on how to use swagger for this spec

### ISSUE THREAD

**Issue by summa-code** [polygon-io/platform-specs#85]
So, what do we make of this line ?

If you want to view the specs locally for a sanity check run ./_bin_/spec_ui and go to http://localhost:8080. Note: This is the Swagger UI view, not the custom Polygon.io view.

Do we have to work with Petstore example ?

**Comment by mmoghaddam385** [comment]
Hi @summa-code, this is a bug, thanks for pointing it out! The `./_bin_/spec_ui` script is looking for the swagger spec by the wrong name (the name was recently changed). Swagger-UI is defaulting to the petstore example because it can't find the right spec.

I'll make a PR fixing this shortly, but in the meantime, you can edit your local copy of `./_bin_/spec_ui` and change line 10 from
```
-e SWAGGER_JSON="/spec/spec.json" \
```
to 
```
-e SWAGGER_JSON="/spec/rest.json" \
```

(change `spec.json` to `rest.json`)
